### ISSUE TITLE
'NameConstraints' object has no attribute 'public_bytes'

### ISSUE THREAD

**Issue by nickperry** [aws-samples/aws-private-ca-enforce-dns-name-constraints#3]
@ischisler I'm not sure what I'm doing wrong, but I can't get this to work:

```
python3 --version
Python 3.8.10

pip --version
pip 23.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)

pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.8)
Collecting argparse
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Installing collected packages: argparse
Successfully installed argparse-1.4.0

python3 name-constraints-encoder.py -p .dev.example.com,.test.example.com -e .prod.dev.example.com
INFO:root:Permitted Subtrees: [<DNSName(value='.dev.example.com')>, <DNSName(value='.test.example.com')>]
INFO:root:Excluded Subtrees: [<DNSName(value='.prod.dev.example.com')>]
Traceback (most recent call last):
  File "name-constraints-encoder.py", line 102, in <module>
    main()
  File "name-constraints-encoder.py", line 69, in main
    encode_name_constraints(permitted_subtrees, excluded_subtrees)
  File "name-constraints-encoder.py", line 74, in encode_name_constraints
    name_constraint_bytes = name_constraint.public_bytes()
AttributeError: 'NameConstraints' object has no attribute 'public_bytes'
```

**Comment by nickperry** [comment]
Aha - fixed.

```
python3 -m
 pip install -U cryptography
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (2.8)
Collecting cryptography
  Downloading cryptography-39.0.2-cp36-abi3-manylinux_2_28_x86_64.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 5.3 MB/s eta 0:00:00
Collecting cffi>=1.12
  Downloading cffi-1.15.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (442 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 442.7/442.7 kB 4.6 MB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 5.0 MB/s eta 0:00:00
Installing collected packages: pycparser, cffi, cryptography
Successfully installed cffi-1.15.1 cryptography-39.0.2 pycparser-2.21


python3 name-constraints-encoder.py -p .dev.example.com,.test.example.com -e .prod.dev.example.com
INFO:root:Permitted Subtrees: [<DNSName(value='.dev.example.com')>, <DNSName(value='.test.example.com')>]
INFO:root:Excluded Subtrees: [<DNSName(value='.prod.dev.example.com')>]
INFO:root:Successfully Encoded Name Constraints. Writing to file...
INFO:root:API Passthrough File Created: api_passthrough_config.json
```

**Comment by nickperry** [comment]
@ischisler perhaps it is worth mentioning in the readme that in addition to updating pip you also need a minimum version of cryptography.

`python3 -m
 pip install -U cryptography`
